//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.14.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "localizationContainer"
	/// <summary>Localization container</summary>
	public partial interface ILocalizationContainer : IPublishedContent
	{
		/// <summary>Default language</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.0")]
		global::Umbraco.Web.Models.Link TDefaultLanguage { get; }

		/// <summary>Language - About Page</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.0")]
		global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.LocalizationLanguageItems> TLanguageAboutPage { get; }
	}

	/// <summary>Localization container</summary>
	[PublishedModel("localizationContainer")]
	public partial class LocalizationContainer : PublishedContentModel, ILocalizationContainer
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.0")]
		public new const string ModelTypeAlias = "localizationContainer";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<LocalizationContainer, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public LocalizationContainer(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Default language
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.0")]
		[ImplementPropertyType("tDefaultLanguage")]
		public virtual global::Umbraco.Web.Models.Link TDefaultLanguage => GetTDefaultLanguage(this);

		/// <summary>Static getter for Default language</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.0")]
		public static global::Umbraco.Web.Models.Link GetTDefaultLanguage(ILocalizationContainer that) => that.Value<global::Umbraco.Web.Models.Link>("tDefaultLanguage");

		///<summary>
		/// Language - About Page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.0")]
		[ImplementPropertyType("tLanguageAboutPage")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.LocalizationLanguageItems> TLanguageAboutPage => GetTLanguageAboutPage(this);

		/// <summary>Static getter for Language - About Page</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.14.0")]
		public static global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.LocalizationLanguageItems> GetTLanguageAboutPage(ILocalizationContainer that) => that.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.LocalizationLanguageItems>>("tLanguageAboutPage");
	}
}
